name: Pixel Bypass

on:
  workflow_dispatch:

env:
  SECRET_URL: ${{secrets.SECRET_URL}}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Requirements
        run: pip install -U -r requirements.txt

      - name: Run main script
        run: python main.py

